### ISSUE TITLE
Users > El campo 'Phone' se comporta como un campo 'Email'

### ISSUE THREAD

**Issue by epardo-23** [ASVclass/bug-validation-site#10]
**Description:**
El campo 'Phone' retorna un mensaje de error solicitando que se ingrese un arroba, lo correcto es que solo permita numeros enteros positivos.

El mensaje de error mostrado es: "Please include an @ in the email address"

**Pasos:**
1. Ingresar a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir al tab 'Add Users'
3. En el campo 'Phone' ingresar un numero válido
4. Click en el botón 'Sign In'

**Actual Result:**
Si se llena un numero válido en el campo 'Phone' retorna un mensaje de error que le pertenece al campo 'Email'
**Expected Result:**
El campo 'Phone' solamente deberia permitir ingresar números válidos

**Comment by miltongutierrezherbas** [comment]
NO SE PUDO REPRODUCIR EL BICHO...
LE FALTA UN PASO PARA QUE REPRODUZCA EL BICHO:

PASO 4 HACER CLICK EN EL BOTON "Sing In"

![image](https://user-images.githubusercontent.com/20774495/113223183-96379580-9256-11eb-9b40-1f7299f54183.png)

**Comment by epardo-23** [comment]
**QA Status 03/31/2021**
**Version**: 35

El bug fue solucionado, ya permite la adición de números y no muestra ningun mensaje de error:
![image](https://user-images.githubusercontent.com/62032357/113225282-3c859a00-925b-11eb-8b70-b5287e4c2814.png)

**Comment by epardo-23** [comment]
**QA Status 04/05/2021**
**Version: 37**

El bug fue validado nuevamente y continua funcionando bien:
- Añadir un nuevo 'phone' ✅
- Permite añadir numeros ✅
- No retorna mensajes de error que corresponden a otro campo. ✅
