### ISSUE TITLE
Users > An Internal Server Error is returned after creation a new user

### ISSUE THREAD

**Issue by epardo-23** [ASVclass/bug-validation-site#11]
**Descripción:**
Un nuevo usuario deberia poder crearse sin problemas si mandas todos los campos requeridos, pero no lo esta haciendo.

![image](https://user-images.githubusercontent.com/62032357/113073513-3928da80-9197-11eb-8028-c4e43d86c8d7.png)

**Pasos:**
1. Ingresar a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2. Ir al tab 'Add Users'
3. Llenar todos los campos requeridos
4. Click en 'Sign In'

**Actual Result:**
Despues de hacer click en 'Sign In' retorna un error con el server (500)
**Expected Result:**
Se deberia crear un nuevo usuario sin problemas

**Comment by giovanaAA** [comment]
Si pasa. 
Recomendación,  podrías especificar que el Developer Tools para vizualizar el error que se menciona (error 500)

**Comment by epardo-23** [comment]
**QA Status 03/31/2021**
**Version**: 35

El bug fue arreglado, ya se puede crear un nuevo usuario y no sale ningun error:
![image](https://user-images.githubusercontent.com/62032357/113225099-d6991280-925a-11eb-9ae0-3d6c50376a7b.png)

**Comment by epardo-23** [comment]
QA Status 04/05/2021
Version: 37

El bug fue verificado nuevamente en la version 37 y continua funcionando correctamente.
- Crear nuevo usuario
- Ver el usuario creado (/)
