### ISSUE TITLE
List Users > El tab 'List Users' es redireccionado a la sección 'Edit Users'

### ISSUE THREAD

**Issue by epardo-23** [ASVclass/bug-validation-site#12]
**Descripción:**
Cuando el ususario ingresa al tab 'List Users'  ingresa el tab incorrecto de 'Edit Users'

![image](https://user-images.githubusercontent.com/62032357/113073676-8ad16500-9197-11eb-98dd-df527d1cf240.png)

**Pasos:**
1. Ingresar a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir al tab 'List Users'
3. Revisar a qué url esta redireccionando

**Actual Result:**
El tab 'List Users' abre una pagina incorrecta 'Edit Users'
**Expected Result:**
El tab 'List Users' deberia abrir la url que le corresponde

**Comment by olimpiacf** [comment]
El bug https://github.com/ASVclass/bug-validation-site/issues/12 es reproducible

se deberia agregar los requerimientos para reproducir el bug

**Comment by epardo-23** [comment]
**QA Status 03/31/2021**
**Version**: 35
El bug ya fue arreglado, procediendo a cerrar:
![image](https://user-images.githubusercontent.com/62032357/113224906-73a77b80-925a-11eb-84be-63397f30a8f7.png)

**Comment by epardo-23** [comment]
**QA Status 04/05/2021**
**Version: 37**

El bug fue validado nuevamente en la ultima version 37 y continua funcionando correctamente
