### ISSUE TITLE
El campo de Last Name oculta los caracteres

### ISSUE THREAD

**Issue by SilviaMercado** [ASVclass/bug-validation-site#13]
PRIORIDAD: Alto
DESCRIPCION: Cuando el usuario selecciona la opcion de Add Users; y empieza el llenado de sus datos, en campo del apellido, al escribir este aparece con asteriscos.
Requisitos: Tener acceso a internet, una computadora, navegar web.
PASOS: 
1. Ingresar a: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Seleccionar: Add Users
3. Realizar el llenado de los datos, haciendo clic en el campo de Last Name
RESULTADO FINAL: Al ingresar cualquier carácter este aparece en asterisco.
RESULTADO ESPERADO: En el campo de Las Name debe visualizarse los caracteres ingresados.

**Comment by ASVclass** [comment]
@Rossy

**Comment by rossymarymarca** [comment]
Se consigio reproducir el error siguiendo los pasos.
Sugerirencia: Quizas se pueda especificar la descripcion ya que   al llenar los campos de Last Name este muestra puntos y no asteriscos.

**Comment by ASVclass** [comment]
Nuevo build ha sido deployado, verificar @rossymarymarca

**Comment by SilviaMercado** [comment]
Sección:  Add Users
La página fue actualizada, el campo de **Last Name** no reporta ningún error.
Resultado Esperado: Se visualizan correctamente los caracteres ingresados
Se puede verificar en la siguiente imagen
![image](https://user-images.githubusercontent.com/81659699/113638811-b6e06080-9645-11eb-9389-3fb21e351031.png)
