### ISSUE TITLE
La contraseña no se encripta cuando se introduce en el campo "Password" 

### ISSUE THREAD

**Issue by giovanaAA** [ASVclass/bug-validation-site#14]
Prioridad: Mayor
Descripción: Cuando se introduce una contraseña en el campo "Password" no se encripta.
Requisitos: 
-Un navegado

Pasos: 
1. - Entrar al link: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Entrar a la ventana  "Add Users"
3. Escribir una contraseña en el campo "Password"
Resultado Actual: No se encripta la contraseña que se introdujo.
Resultado Esperado: La contraseña debe ser encriptada.

**Comment by ASVclass** [comment]
@omar

**Comment by ASVclass** [comment]
@eloy

**Comment by giovanaAA** [comment]
Se corrigió el bug, ahora se encripta la contraseña que se introduce en el campo "Password"

**Comment by giovanaAA** [comment]
Se corrigió el bug, ahora se encripta la contraseña que se introduce en el campo "Password"
