### ISSUE TITLE
El campo LastName del formulario de AddUser se encuentra formato password

### ISSUE THREAD

**Issue by rickyasg** [ASVclass/bug-validation-site#16]
**Prioridad**: alta
Descripcion: cuando se registra un nuevo usuario el campo LastName del formulario Add Users presenta la apariencia tipo password, este bug fue probado en navegadores chrome y firefox
**Requisitos**: 
1. Un navegador  de internet
2. Informacion de nuevo usuario para registro (First Name, Last Name, Password, Phone, Email)
**Pasos:**
1. ingresar al sitio https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2. Registrar informacion de usuario en el campo LastName
**Resultado Actual**
El Campo LastName al escribir muestra el caracter * por cada letra escrita
**Resultado Esperado:**
Se debe visualizar la informacion registrada en el campo LastName en formato texto

**Comment by ASVclass** [comment]
@omarob201

**Comment by Omarob201** [comment]
Pude reproducir con los pasos el bug, la prioridad quizas no sea alta, no es un requisito tener la información de nuevo usuario

**Comment by rickyasg** [comment]
el bug fue solucionado en el release 35

**Comment by rickyasg** [comment]
Ya no se reproduce el bug, fue corregido en la version 32
Nota de Testeo:
Se realizo la validacion en el ambiente de QA
Se uso un navegador Chrome
Despues llenar la informacion  LastName del formulario UserAdd ya no se encuentra en formato password.
![image](https://user-images.githubusercontent.com/30187370/113639681-b0eb7f00-9647-11eb-99c3-37bf6ee6371a.png)
