### ISSUE TITLE
El campo de Password no oculta los caracteres ingresados

### ISSUE THREAD

**Issue by SilviaMercado** [ASVclass/bug-validation-site#21]
PRIORIDAD: Alto
DESCRIPCION: Cuando el usuario selecciona la opcion de Password; y realiza el llenado de su contraseña, al escribir este NO aparece con asteriscos.
Requisitos: Tener acceso a internet, una computadora, navegar web.
PASOS: 
1. Ingresar a: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Seleccionar: Add Users
3. Realizar el llenado de los datos, haciendo clic en el campo de Password
RESULTADO FINAL: Al ingresar cualquier carácter este NO aparece en asterisco.
RESULTADO ESPERADO: En el campo de Password todo lo ingresado debe aparecer con asterisco.

**Comment by epardo-23** [comment]
Bien, pude reproducir el bug, contiene los pasos necesarios.

Como sugerencias:
 - Ya que la cantidad de bugs iran incrementando a lo largo del desarrollo del proyecto, es bueno poner en el titulo el sitio donde esta pasando el bug. Por ej: seccion 'Add Users'
 - Sería bueno contar con una captura, para identificar más rapidamente donde pasa el bug.
 - El reporte del bug se podria mejorar dandole un formato adecuado, espacios, mayúsculas, minúsculas, negritas, etc.

**Comment by ASVclass** [comment]
Nuevo build ha sido deployado, verificar

**Comment by SilviaMercado** [comment]
Sección:  Add Users
La página fue actualizada, el campo de **Password** no reporta ningún error.
Resultado Esperado: Al ingresar los caracteres estos aparecen encriptados
Se puede verificar en la siguiente imagen
![image](https://user-images.githubusercontent.com/81659699/113639027-438b1e80-9646-11eb-8384-90fcf942ca7b.png)
