### ISSUE TITLE
Users > Permite create un nuevo user sin mandar los campos requeridos(marcados en *)

### ISSUE THREAD

**Issue by epardo-23** [ASVclass/bug-validation-site#22]
**Descripción:**
Si el usuario no manda los required fields marcados en asterisco, la pagina deja proseguir la creación de un nuevo usuario.

![image](https://user-images.githubusercontent.com/62032357/113074100-6f1a8e80-9198-11eb-823f-5d931a557df5.png)

**Pasos:**
1. Ingresar a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2. Ir al tab 'Add Users'
3. Llenar los campos NO requeridos: 'password' y 'phone'
4. Click en 'Sign In'

**Actual Result:**
Permite continuar el proceso de creación de usuarios solamente con campos NO requeridos

**Expected Result:**
La página web deberia mostrar un mensaje de error si no se llena todos los campos requeridos y no permitir crear un nuevo usuario

**Comment by dangelsc** [comment]
No puedo reproducir,  se pausa en el paso 4, validando el Phone

**Comment by ASVclass** [comment]
Nuevo build ha sido deployado, verificar

**Comment by epardo-23** [comment]
**QA Status 04/05/2021**
**Version: 37**

El bug ya **NO** se reproduce, debido a que ahora muestra un mensaje de error solicitando llenar los campos requeridos(ver imagen)
![image](https://user-images.githubusercontent.com/62032357/113638860-d7101f80-9645-11eb-95ca-b27544573045.png)

además se validó que:
- El campo 'First Name' es requerido. ✅
- El campo 'Last Name' es requerido. ✅
- El campo 'Email' es requerido. ✅
