### ISSUE TITLE
El campo Password del formulario UserAdd no se encuentra en formato encriptado

### ISSUE THREAD

**Issue by rickyasg** [ASVclass/bug-validation-site#24]
**Prioridad**: alta
Descripcion: cuando se registra un nuevo usuario el campo Password muestra la informacion escrita esta debe tener la propiedad Password asignada, este bug fue probado en navegadores chrome y firefox
**Requisitos**: 
1. Un navegador  de internet
2. Informacion de nuevo usuario para registro (First Name, Last Name, Password, Phone, Email)
**Pasos:**
1. ingresar al sitio https://qa-bugs-hunting-demo-site.herokuapp.com/add-user
2. Registrar informacion de usuario en el campo Password
**Resultado Actual**
El Campo muestra la informacion del password del usuario
![image](https://user-images.githubusercontent.com/30187370/113074625-6d04ff80-9199-11eb-99e9-72865a41aa85.png)
**Resultado Esperado:**
Se debe utilizar asignar la propiedad Password al input y poder encriptar la informacion del usuario

**Comment by rickyasg** [comment]
ya se encuentra solucionado en la version 32

**Comment by ASVclass** [comment]
Podrias agregar mas informacion a la validacion por favor

**Comment by rickyasg** [comment]
Ya no se reproduce el bug, fue corregido en la version 32
**Nota de Testeo:**
Se realizo la validacion en el ambiente de QA
Se uso un navegador Chrome
Despues llenar la informacion del formulario UserAdd ya se encuentra en formato password.
![image](https://user-images.githubusercontent.com/30187370/113639546-65d16c00-9647-11eb-9d42-8995ec4c3174.png)
