### ISSUE TITLE
Validación incorrecta el en carácter Phone

### ISSUE THREAD

**Issue by miltongutierrezherbas** [ASVclass/bug-validation-site#26]
Prioridad: high

Descripción: Dentro el formulario del menú "Add user" cuando se taipea el telefono en el label "Phone", se hace click en el boton Sing In, valida el campo como si fuera un email pidiendo que se incluya un signo @ 

Requisitos: navegador de internet

Pasos:

-ingresar a la dirección "https://qa-bugs-hunting-demo-site.herokuapp.com/"
-Ingresar al menú en la parte superior derecha "Add Users"
-Taipear '78455' en el label "Phone"
-Click en el boton Sing In
-notese que la validadcion en el campo Phone es incorrecta , pidiendo que se incluta un soigno @

Resultado actual : La validadcion en el campo Phone se la realiza como si fuera un email

![image](https://user-images.githubusercontent.com/20774495/113074187-9d986980-9198-11eb-9ea2-bc7347e2f0cd.png)

Resultado esperado: la validacion del label Phone no deberia ser como si fuera un email

**Comment by miltongutierrezherbas** [comment]
el bug se corrigió en el ultimo reléase.... se cierra EL BUG

**Comment by ASVclass** [comment]
Podrias agregar mas informacion a la validacion por favor
