### ISSUE TITLE
the text box Last Name hiden the information like being a password

### ISSUE THREAD

**Issue by lissCL** [ASVclass/bug-validation-site#29]
Severity : medium
DESCRIPTION: when introduce the last name, automaticaly hiden the information like being a password
requirements:
- browser
- have open the following web url https://qa-bugs-hunting-demo-site.herokuapp.com/
STEPS:
1- go to https://qa-bugs-hunting-demo-site.herokuapp.com/
2-click on AddUser in the menú on the top right of the screem.
ACTUAL RESULT: the last name on the texbox hiden the information like being a password
SPECT RESULT:  that the Last name  is show exactly like were introduced, without hiden it.

![Snag_38e82715](https://user-images.githubusercontent.com/29043130/113161477-6bc0ea80-920c-11eb-9e51-f6e0aafd30d5.png)

**Comment by ASVclass** [comment]
pude reproducir con los pasos del bug

**Comment by ASVclass** [comment]
Nuevo build fue deployado, verificar

**Comment by lissCL** [comment]
El nuevo release solucionó el bug reportado.
la funcionalidad en la v37
verificado en el navegador Edge.
