### ISSUE TITLE
  Al agregar un nuevo User las funciones Edit y Delete no funcionan.

### ISSUE THREAD

**Issue by rossymarymarca** [ASVclass/bug-validation-site#37]
PRIORIDAD: Alto
DESCRIPCION: Cuando el usuario Agrega un nuevo registro Add Users las opciones Edit y Delete lo funcionan.
Requisitos: Tener acceso a internet, una computadora, navegar web.
PASOS:

- Ingresar a: https://qa-bugs-hunting-demo-site.herokuapp.com/
- Seleccionar  la opcion Add Users
- Llenar los campos del registro Add User y guardar.
- Seleccionar la opcion edit User y  buscar el registro creado.
- Presionar el boton Delete 
- Presionar el boton Edit

RESULTADO FINAL: Al presionar el boton Delete o Edit este me muestra una pantalla donde indica que no funciona.
RESULTADO ESPERADO: Al presionar el boton Edit deberia mostrarme la ventana de registro permitiendo editar los campos, de la misma manera al presionar el boton Delete deberia mostrar un mensaje de confirmacion para eliminar.
![MENSAJE DE ERROR](https://user-images.githubusercontent.com/69520189/113638419-cb702900-9644-11eb-897c-bcd0b559da8b.jpg)

**Comment by ASVclass** [comment]
No olvides anadir screenshots de los mensajes, tambien al hacer web testing abrir el Web tools para ver si se muetra algun error
