### ISSUE TITLE
"Add User" form: "Last Name *" field no muestra el texto ingresado

### ISSUE THREAD

**Issue by GermanFrontanilla** [ASVclass/bug-validation-site#50]
**Severidad**: Mayor

**Descripción**: Cuando el usuario ingresa texto en "Last Name *" field para "Add User" form el texto ingresado no es mostrado

**Requerimientos**
Browser Chrome (ultima version)

**versión:** 35
**Steps**
1- Ir a la página "https://qa-bugs-hunting-demo-site.herokuapp.com/"
2- Click en "Add User" link
3- Escribir en "Last Name *" field

**Resultado Actual**: El texto ingresado en "Last Name *" field no es mostrado

**Resultado Esperado**: El texto ingresado en "Last Name *" field debería ser mostrado

**Comment by ErvSan21** [comment]
Notas de testeo:
Agregar version, 35

Se pudo reproducir el bug, agregando captura:
![image](https://user-images.githubusercontent.com/91227228/137229900-0afdb551-06b6-4956-8077-95a32b244e81.png)

**Comment by elviaAr** [comment]
**Notas de testeo:** Tal vez se puede agregar que el texto que se ingresa se muestra encriptado (como usualmente es el comportamiento en los campos de contraseña).
Se pudo reproducir el error.

**Comment by GermanFrontanilla** [comment]
**Notas de testeo:** El defecto ya no se reproduce, con el build "37" el campo "Last Name*" muestra el texto ingresado por el usuario.

**Estimación:** 5 min

**Ambiente:** QA

**Browser:** Chrome 

El defecto ya no se reproducen adjunto imagen.
![Captura de pantalla (5)](https://user-images.githubusercontent.com/36299326/137821292-081e6864-ba35-42c2-b4d3-49045b331116.png)
