### ISSUE TITLE
Add Users - Internal Server Error al crear un usuario con campos en blanco

### ISSUE THREAD

**Issue by elviaAr** [ASVclass/bug-validation-site#52]
**Severidad:** Media

**Descripcion:** Cuando se intenta crear un usuario con los campos en blanco, el siguiente mensaje es desplegado:
Internal Server Error
**The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

**Requerimientos**
Browser Chrome ultima version (ventana incognita)
Versión: 35

**Steps**

1. Ir a la pagina: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a la opcion 'Add Users'
3. Dejar todos los campos en blanco
4. Click en el boton 'Sign in'

**Actual Result**
Internal Server Error es desplegado en la pantalla

**Expected Result**

Un mensaje de validacion deberia mostrarse aclarando que los campos no deben dejarse vacios

**Comment by Joseleban** [comment]
Notas de testeo

Si pude reproducir el bug con los pasos listado
![image](https://user-images.githubusercontent.com/92490982/137230291-1a4712da-da1a-4240-bd09-31041967e1ee.png)

**Comment by Joseleban** [comment]
corregido

![image](https://user-images.githubusercontent.com/92490982/137231810-b7b08786-3be8-4ca2-a124-fdfd893a4438.png)

**Comment by elviaAr** [comment]
**Tested Build:** 37
**OS:** Windows 10
**Fecha** 10.18.2021
**Resultado:** Passed
**Notas de QA**: Usando el browser: Chrome
