### ISSUE TITLE
"Add User" form: El usuario no es creado ingresando teléfono valido en "Phone" field 

### ISSUE THREAD

**Issue by GermanFrontanilla** [ASVclass/bug-validation-site#55]
**Severidad**: Mayor

**Descripción**: Cuando el usuario ingresa un número de teléfono válido en "Phone" field para "Add User" form no puede crear un usuario
**Requerimientos**
Browser Chrome (ultima version)

**Versión**: 35

**Steps**
1- Ir a la página "https://qa-bugs-hunting-demo-site.herokuapp.com/"
2- Click en "Add User" link
3 - Llenar todos los campos requeridos
4- Escribir un teléfono valido en "Phone" field por ejm (72771834)
5- Click en "Sign In" button

**Resultado Actual**: El siguiente mensaje de alerta es mostrado "Incluye un signo de "@" en la dirección de correo electrónico la dirección "72771834" no incluye el sigo "@""

**Resultado Esperado**: El usuario debería ser creado correctamente

**Comment by Carlos152915** [comment]
Notas de testing: Se pudo replicar el error, y el mismo será subsanado por el área de desarrollo.

**Comment by GermanFrontanilla** [comment]
Notas de testeo: El defecto ya no se reproduce, con el build "37" el usuario es creado ingresando un número de teléfono válido en "Phone" field.

Estimación: 5 min

Ambiente: QA

Browser: Chrome

El defecto ya no se reproducen adjunto imagen.

![Captura de pantalla (4)](https://user-images.githubusercontent.com/36299326/137821535-61d0dc0f-fc1d-4d7d-955d-c79f6492a125.png)
