### ISSUE TITLE
Add Users - Validacion del campo 'Email' se esta aplicando para el campo 'Phone'

### ISSUE THREAD

**Issue by elviaAr** [ASVclass/bug-validation-site#57]
**Severidad:** Alta

**Descripcion:** Cuando creo un usuario y en el campo email añado un correo valido, la validacion se muestra para el campo 'Phone', el siguiente mensaje es desplegado:
Please include an '@' in the email address. 'PhoneValue' is missing an '@'

**Requerimientos**
Browser Chrome ultima version (ventana incognita)
Versión: 35

**Steps**

1. Ir a la pagina: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a la opcion 'Add Users'
3. Llenar todos los campos con datos validos (tome nota del email ingresado)
4. Click en el boton 'Sign in'

**Actual Result**
El usuario no se crea y el siguiente mensaje es desplegado: Please include an '@' in the email address. 'PhoneValue' is missing an '@'

Expected Result
El usuario deberia crearse exitosamente con la informacion proporcionada en el paso 3.

**Comment by ErvSan21** [comment]
Notas de testeo:

Se pudo reproducir el bug, agregando captura:
![image](https://user-images.githubusercontent.com/91227228/137230081-53da1b3f-5417-4971-8d7e-26c0a5ff3c05.png)

**Comment by elviaAr** [comment]
Notas de testeo: Se pudo reproducir el error .

**Comment by elviaAr** [comment]
Notas de testeo: Defecto fue arreglado.
