### ISSUE TITLE
Bugs: Error al guardar usuario

### ISSUE THREAD

**Issue by construido** [ASVclass/bug-validation-site#6]
@ASVclass

**Comment by construido** [comment]
Se sigue reproduciendo el bugs

**Comment by ASVclass** [comment]
Pasos para reproducir

1. abrir https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a "Add Users"
3. Llenar el formulario con informacion valida
4. Click "Sign In"

**Comment by ASVclass** [comment]
**Notas de testeo**
 Se realizo la validacion en QA env.
usando browser Chrome  modo incognito 

Despues de llenar el formulario y presionar "Sign in"  no se muestra error y hay un mensaje de que el contacto fue agregado exitosamente

![image](https://user-images.githubusercontent.com/81577422/113227379-90df4880-9260-11eb-9a7d-d5a3998e1426.png)

El nuevo usuario se encuntra listado

![image](https://user-images.githubusercontent.com/81577422/113227458-be2bf680-9260-11eb-840d-9a326ccde1ec.png)
