### ISSUE TITLE
Add Users - Internal Server Error al crear un usuario con informacion valida

### ISSUE THREAD

**Issue by elviaAr** [ASVclass/bug-validation-site#61]
**Severidad:** Blocker

**Descripcion:** Cuando se intenta crear un usuario con informacion valida, el siguiente mensaje es desplegado:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Requerimientos**
Browser Chrome ultima version (ventana incognita)
Versión: 35

**Steps**

1. Ir a la pagina: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a la opcion 'Add Users'
3. Llenar todos los campos con informacion valida, por ejemplo: 
First Name: Elvia
Last Name: Arguedas
Password: Control123
Phone: 4253616
Email: elvia@test.com
4. Click en el boton 'Sign in'

**Actual Result**
Internal Server Error es desplegado en la pantalla

**Expected Result**
Usuario debe crearse exitosamente con la informacion proporcionada en el paso 3

**Comment by NancyC01** [comment]
Notas de testeo:
Se pudo reproducir el bug

**Comment by elviaAr** [comment]
**Tested Build:** 37
**OS:** Windows 10
**Fecha** 10.18.2021
**Resultado:** Arreglado
**Notas de QA**: Usando el browser: Chrome
