### ISSUE TITLE
La informacion que se muestra en la pestaña "List Users" es erronea

### ISSUE THREAD

**Issue by ErvSan21** [ASVclass/bug-validation-site#63]
**Severidad:** Media

Al acceder a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/, e intentar dirigirse a la pestaña List Users esta muestra la información de Edit Users

**Requerimientos**
Acceso a navegador Google Chrome

**Pasos**
1.-Ingrese a https://qa-bugs-hunting-demo-site.herokuapp.com/
2.-Dirijase a List Users en la parte superior derecha
3.-Click en List users

**Resultado Actual**
Se muestra la información Edit Users

**Resultado esperado**
Se muestra la información de List Users

**Comment by ASVclass** [comment]
Notas de testeo
 Agregar version, 35

Si pude reproducir el bug con los pasos listados, anadiendo imagen
