### ISSUE TITLE
Se logra registrar un usuario solo ingresando el campo First Name

### ISSUE THREAD

**Issue by Carlos152915** [ASVclass/bug-validation-site#77]
Prioridad: Alta.

Severidad: Alta

Descripción: La aplicación permite registrar usuarios solo ingresando el campo First Name, a pesar de no llenar los campos obligatorios 

Requerimientos:

Buscador Chrome
Versión 37 de la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/.

Pasos:

Abrir el buscador.

Ir a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/
Ingresar a la sección Add User.
Ingresar un  nombre en el campo First Name.
Presionar el boton Sing in.
Resultado Actual: el registro es exitoso.
Resultado Esperado: La aplicación debe obligar al usuario a ingresar todos los campos obligatorios
![2021-10-18_20-01-48](https://user-images.githubusercontent.com/92411601/137822386-ae84ff5a-db02-448f-82c4-2bf2101dda28.png)
.

**Comment by GermanFrontanilla** [comment]
asignado a germán frontanilla

**Comment by GermanFrontanilla** [comment]
Notas de testeo: El defecto ya no se reproduce, con el build "41" el mensaje "completa este campo" es desplegado al hacer click en el boton "Sign in" llenando solo el campo "First Name"

Estimación: 5 min

Ambiente: QA

Browser: Chrome

El defecto ya no se reproducen adjunto imagen.

![Captura de pantalla (8)](https://user-images.githubusercontent.com/36299326/137825803-7fa0e3f5-660d-4b8c-aed9-e64ed816a932.png)
