### ISSUE TITLE
Add Users - Es posible añadir un nuevo usuario solo con el dato requerido de 'First Name'

### ISSUE THREAD

**Issue by elviaAr** [ASVclass/bug-validation-site#78]
**Severidad:** Alta

**Descripcion:** Cuando creo un nuevo usuario llenando solo el campo 'First Name', el usuario es exitosamente creado no tomando en cuenta los otros campos requeridos como: Last Name y Email.

**Requerimientos**
Browser Chrome ultima version (ventana incognita)
Versión: 37

**Steps**
1. Ir a la pagina: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a la opcion 'Add Users'
3. Llenar solo el campo First Name
4. Click en el boton 'Sign in'

**Actual Result**
El usuario se crea exitosamente.

**Expected Result**
Un mensaje de validacion deberia mostrarse aclarando que todos los campos requeridos deben llenarse para crearse un nuevo usuario.

**Comment by GermanFrontanilla** [comment]
issue asignado a germán frontanilla

**Comment by GermanFrontanilla** [comment]
Notas de testeo: El defecto ya no se reproduce, con el build "41" el mensaje "completa este campo" es desplegado al hacer click en el boton "Sign in" llenando solo el campo "First Name"

Estimación: 5 min

Ambiente: QA

Browser: Chrome

El defecto ya no se reproducen adjunto imagen.
![Captura de pantalla (8)](https://user-images.githubusercontent.com/36299326/137825718-665750ec-1c4f-4255-a8fc-b45816e89cea.png)
