### ISSUE TITLE
El campo "Last Name"  encripta la palabra que se escribe en ella.

### ISSUE THREAD

**Issue by giovanaAA** [ASVclass/bug-validation-site#8]
Prioridad: Mayor
Descripción: Cuando se escribe en el campo "Last Name" las palabras son encriptados.
Requisitos: 
-Un navegado

Pasos: 
1. - Entrar al link: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Entrar a la ventana  "Add Users"
3. Escribir en el campo "Last Name" un apellido cualquiera.
Resultado Actual:  Al escribir en el campo "LastName" muestra la información en un estilo de password, reemplazando las letras por el simbolo *
Resultado Esperado:  Al escribir en el campo "LastName" no debe ser  encriptada.

**Comment by rickyasg** [comment]
Se pudo reproducir el bug.
-Se sugiere en la descripcion solo utilizar un termino, LastName, Apellido.
-En el Resultado actual, se recomienda detallar mas el resultado actual.Ej. Al escribir en el campo LastName muestra la informacion en un estilo de password, reemplazando las letras por el simbolo *
-En el Resultado Esperado, se recomienda detallar mas el resultado actual.Ej. Al escribir en el campo LastName no debe contar la apariencia encriptada.

**Comment by giovanaAA** [comment]
Ya no se reproduce el bug, ya se corrigío.
Nota de testeo:
Se realizo la validación en un ambiente QA.
Se usó un navegador Chrome.
Despúes de llenar con información el campo "LastName" de la pestaña "Add Users" la información ya no se muestra encriptada.

Imagen adjunto:
![LastName](https://user-images.githubusercontent.com/8507526/113228311-9047b180-9262-11eb-8d95-98c60ab7cba6.png)
