### ISSUE TITLE
"List Users" section: "Not Found" mensaje de error al hacer click en el boton "delete"

### ISSUE THREAD

**Issue by GermanFrontanilla** [ASVclass/bug-validation-site#83]
**Severidad:** Blocker

**Descripción:** Cuando el usuario hace click en el boton "delete" en "List Users" section el mensaje de error "Not Found" es desplegado

Requerimientos:
Browser Chrome (ultima version)

Versión: 37

**Pre-condiciones:** Tener al menos un usuario creado

**Steps:**
1- Ir a la página "https://qa-bugs-hunting-demo-site.herokuapp.com/"
2- Click en "List Users" link
3 - Buscar por el usuario creado
4- Click en el boton "delete"

**Resultado Actual:** El siguiente mensaje de alerta es mostrado "Not Found"

![Captura de pantalla (7)](https://user-images.githubusercontent.com/36299326/137822913-b4f1ec84-fd37-4125-b5b3-419a3545d1c0.png)

**Resultado Esperado:** El usuario debería ser eliminado

**Comment by elviaAr** [comment]
**Notas de testeo:** Elvia trabajara en este ticket

**Comment by elviaAr** [comment]
**Tested Build:** 41
**OS:** Windows 10
**Fecha:** 10.18.2021
**Resultado:** Cerrado como 'No reproducible'
**Notas de QA:** El error ya no es visible en la version 41, por eso se cierra como 'No reproducible'
Usando el browser chrome
