### ISSUE TITLE
Delete Users - No es posible eliminar un usuario, la pagina 'Not found' es desplegada

### ISSUE THREAD

**Issue by elviaAr** [ASVclass/bug-validation-site#85]
**Severidad:** Alta

**Descripcion:** No se puede eliminar un usuario, la pagina ''Not Found" es desplegada

**Requerimientos**
Browser Chrome ultima version (ventana incognita)
Versión: 37

**Precondiciones**
Tener un usuario creado

**Steps**
1. Ir a la pagina: https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir a la opcion 'List Users'
3. Eliminar el usuario de las precondiciones

**Actual Result**
Pagina 'Not Found' es desplegada

**Expected Result**
El usuario deberia eliminarse exitosamente y no mostrarse en la pagina 'List Users'
![image](https://user-images.githubusercontent.com/82408064/137823419-ebd67607-7d97-4baf-bbb0-5bb079cc1962.png)

**Comment by ErvSan21** [comment]
Estoy trabajando en este ticket

**Comment by ErvSan21** [comment]
Notas de Testeo:
Cerrando el bug ya que en esta nueva versión no se puede reproducir.
Estimacion: 15 minutos
Build 41
Se realiza la validacion en QA
Browser: Google Chrome
