### ISSUE TITLE
La informacion que se muestra en la pestaña "Delete User" no muestra la lista de usuarios borrados

### ISSUE THREAD

**Issue by WilfredoOmar** [ASVclass/bug-validation-site#86]
Severidad: Media

- Al acceder a la pagina **https://qa-bugs-hunting-demo-site.herokuapp.com/**, intentar dirigirse a la pestaña Delete User deberia mostrar los User borrados.

Requerimientos
Acceso a navegador Google Chrome

Pasos
1.-Ingrese a https://qa-bugs-hunting-demo-site.herokuapp.com/
2.-Dirijase a Delete User en la parte superior derecha
3.-Click en Delete Users

Resultado Actual
No muestra la información de los user borrados.

Resultado esperado
Mostrar los user borrados.

**Comment by Carlos152915** [comment]
con la nueva version ya se puede ber la lista de usuarios a ser borrados
