### ISSUE TITLE
Users > El campo 'Last Name' muestra como oculto cuando se ingresa cualquier caracter

### ISSUE THREAD

**Issue by epardo-23** [ASVclass/bug-validation-site#9]
**Description:**
El campo 'Last Name' esta encriptando los valores que se ingresan, similar al que lo deberia hacer el campo 'Password'.

**Pasos:**
1. Ingresar a la pagina https://qa-bugs-hunting-demo-site.herokuapp.com/
2. Ir al tab 'Add Users'
3. Llenar el campo 'Last Name' con algunas palabras

**Actual Result:**
El campo 'Last Name' se muestra encriptado y oculto (como deberia ser el campo password)
**Expected Result:**
El campo 'Last Name' deberia mostrar las palabras que se ingresa y no ocultos

**Comment by lissCL** [comment]
**el Bug si se pudo reproducir correctamente.**
observaciones.
----
1- sería mas claro adjuntar una imagen del error para compararlo.
2- poner la asignación de severidad del bug.

**Comment by epardo-23** [comment]
**QA Status 03/31/2021**
**Version**: 35

El bug ya fue solucionado, el campo 'Last Name' ya no muestra oculto:
![image](https://user-images.githubusercontent.com/62032357/113225373-7787cd80-925b-11eb-9e4e-38818aca30a7.png)

**Comment by epardo-23** [comment]
**QA Status 04/05/2021**
**Version: 37**

El bug fue validado nuevamente y continua funcionando como deberia:
- El campo 'Last Name' no muestra oculto en asteriscos. ✅
- El campo 'Last Name' muestra los caracteres ingresados. ✅
